#!/bin/sh

export LC_ALL=C

set -e
set -x

rm -rf rsget.pl
./svn_snapshot.sh
./file_info.pl
./getter_info.pl
./generator.pl

find rsget.pl -name "index.xml" -o -name "error*.xml" \
	| xargs xmllint --valid >/dev/null

set +x
for PHP in $(find rsget.pl -name "index.php" -o -name "error*.php"); do
	echo "+ xmllint --valid $PHP"
	php $PHP | xmllint --valid - > /dev/null
done
set -x

ask() {
	echo
	echo -n "Update $1 server [y/N] ? "
	read ANS
	[ "$ANS" = "y" ] || exit 0
}

cd rsget.pl

ask "local"
rsync -zctrlP --delay-updates --delete --delete-after \
	. sparky.homelinux.org:public_html/rsget.pl

ask "remote"
rsync -zctrlP --delay-updates --delete --delete-after \
	. szamchat.xatka.net:public_html/rsget.pl

echo "All done !"
